dev:
  app_name: "web-api"
  host: "0.0.0.0"
  port: 4400
  code_sim_service_addr: "localhost:4401"

prd:
  app_name: "web-api"
  host: "0.0.0.0" # for test
  port: 4400
  code_sim_service_addr: "code_sim:4401"