dev:
  app_name: "web-api"
  host: "0.0.0.0"
  port: 4400
  code_sim_service_addr: "localhost:4401"

prd:
  app_name: "web-api"
  host: "1.2.3.4" # for test
  port: 4400
  code_sim_service_addr: "http://code_sim:4401"